spring.application.name=chat-app
server.port=8085
#spring.datasource.url=jdbc:postgresql://localhost:5432/chat_app
#spring.datasource.username=postgres
#spring.datasource.password=Dovancong2004@
#
#spring.datasource.driver-class-name=org.postgresql.Driver
#
## Hibernate JPA
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update

# Logging SQL (t�y ch?n)
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

